FROM ubuntu:18.04
RUN apt-get update -y && \
    apt-get install -y python3-pip && \
    python3 -m pip install flask
ENV FLASK_APP=inv
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
COPY . /app
WORKDIR /app
ENTRYPOINT ["python3"]
CMD ["-m", "flask", "run", "-h", "0.0.0.0", "-p", "8080"]
EXPOSE 8080
